// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangMyPham.Data;

#nullable disable

namespace QuanLyCuaHangMyPham.Migrations
{
    [DbContext(typeof(QLCHMPDbContext))]
    [Migration("20260415195814_ManualFixNCC")]
    partial class ManualFixNCC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.CaLamViec", b =>
                {
                    b.Property<string>("MaCa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCa");

                    b.ToTable("CaLamViec");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.HangSanXuat", b =>
                {
                    b.Property<string>("MaHSX")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenHSX")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("XuatXu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHSX");

                    b.ToTable("HangSanXuat");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiemCongThem")
                        .HasColumnType("int");

                    b.Property<int>("DiemDaDung")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("PT_ThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.HoaDon_ChiTiet", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHD", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("HoTenKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.LichSuHoatDong", b =>
                {
                    b.Property<int>("MaLS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLS"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLS");

                    b.HasIndex("MaTK");

                    b.ToTable("LichSuHoatDong");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.LoaiSanPham", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.NhaCungCap", b =>
                {
                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenNV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PT_ThanhToan", b =>
                {
                    b.Property<string>("MaPT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenPT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPT");

                    b.ToTable("PT_ThanhToan");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhanCa", b =>
                {
                    b.Property<string>("MaPC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaCa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayLam")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPC");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNV");

                    b.ToTable("PhanCa");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhieuChi", b =>
                {
                    b.Property<string>("MaPC")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNCC")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaPT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayChi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTienChi")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPC");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPT");

                    b.ToTable("PhieuChi");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("PT_ThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienDaTra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPN");

                    b.HasIndex("MaNCC");

                    b.HasIndex("MaNV");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhieuNhap_ChiTiet", b =>
                {
                    b.Property<string>("MaPN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPN", "MaSP");

                    b.HasIndex("MaSP");

                    b.ToTable("PhieuNhap_ChiTiet");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHSX")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNCC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SLTon")
                        .HasColumnType("int");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaSP");

                    b.HasIndex("MaHSX");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNCC");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaTK");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.TienIch.CauHinhGiaoDien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CoChu")
                        .HasColumnType("int");

                    b.Property<string>("FontChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauNen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("CauHinhGiaoDien");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.HoaDon", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.HoaDon_ChiTiet", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.HoaDon", "HoaDon")
                        .WithMany("ChiTietHDs")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.SanPham", "SanPham")
                        .WithMany("ChiTietHDs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.LichSuHoatDong", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSuHoatDongs")
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhanCa", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.CaLamViec", "CaLamViec")
                        .WithMany("PhanCas")
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.NhanVien", "NhanVien")
                        .WithMany("PhanCas")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhieuChi", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuChis")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QuanLyCuaHangMyPham.Data.NhanVien", "NhanVien")
                        .WithMany("PhieuChis")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.PT_ThanhToan", "PT_ThanhToan")
                        .WithMany("PhieuChis")
                        .HasForeignKey("MaPT")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");

                    b.Navigation("PT_ThanhToan");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhieuNhap", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhieuNhap_ChiTiet", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPNs")
                        .HasForeignKey("MaPN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.SanPham", "SanPham")
                        .WithMany("ChiTietPNs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.SanPham", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.HangSanXuat", "HangSanXuat")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaHSX")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangMyPham.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HangSanXuat");

                    b.Navigation("LoaiSanPham");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyCuaHangMyPham.Data.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.TienIch.CauHinhGiaoDien", b =>
                {
                    b.HasOne("QuanLyCuaHangMyPham.Data.NhanVien", "NhanVien")
                        .WithOne("CauHinhGiaoDien")
                        .HasForeignKey("QuanLyCuaHangMyPham.TienIch.CauHinhGiaoDien", "MaNV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.CaLamViec", b =>
                {
                    b.Navigation("PhanCas");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.HangSanXuat", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.HoaDon", b =>
                {
                    b.Navigation("ChiTietHDs");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.NhaCungCap", b =>
                {
                    b.Navigation("PhieuChis");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.NhanVien", b =>
                {
                    b.Navigation("CauHinhGiaoDien")
                        .IsRequired();

                    b.Navigation("HoaDons");

                    b.Navigation("PhanCas");

                    b.Navigation("PhieuChis");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("TaiKhoan")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PT_ThanhToan", b =>
                {
                    b.Navigation("PhieuChis");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPNs");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.SanPham", b =>
                {
                    b.Navigation("ChiTietHDs");

                    b.Navigation("ChiTietPNs");
                });

            modelBuilder.Entity("QuanLyCuaHangMyPham.Data.TaiKhoan", b =>
                {
                    b.Navigation("LichSuHoatDongs");
                });
#pragma warning restore 612, 618
        }
    }
}
